config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'municipes#index'
  devise_for :users
  resources :municipes, except: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
	belongs_to :municipe
	validates :zipcode, :address, :complement, :city, :neighborhood, :state, presence: true
end

app/models/municipe.rb
# frozen_string_literal: true

class Municipe < ApplicationRecord
  has_one_attached :photo
  has_one :endereco
  accepts_nested_attributes_for :endereco, allow_destroy: true

  validates :name, :cpf, :cns, :email, :birthdate, :phone, :photo, presence: true
  validates :status, inclusion: { in: [true, false] }
  validates :name, format: { with: /([\w\-']{2,})(\s+)([\w\-']{2,})/ }, if: :name
  validates :cpf, length: { is: 11 }
  validate :valid_cpf, if: :cpf
  validate :birthdate_data_range, if: :birthdate
  validates :cns, length: { is: 15 }
  validates :cpf, :cns, numericality: { only_integer: true }
  validates :phone, length: { is: 11 }
  validates :phone, phone: true, if: :phone
  validates_format_of :email, with: Devise.email_regexp, if: :email

  validates :cpf, :email, :phone, :cns, uniqueness: true

  private

  def valid_cpf
    errors.add(:cpf, I18n.t('errors.messages.invalid')) unless CPF.valid?(cpf)
  end

  def birthdate_data_range
    unless ((120.years.ago)..(1.day.ago)).cover?(birthdate)
      errors.add(:birthdate,
                 I18n.t('errors.messages.invalid'))
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: request.host_with_port }
  end
end

app/controllers/municipes_controller.rb
# frozen_string_literal: true

class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[show edit update]

  def index
    @municipes = Municipe.all.decorate
  end

  def new
    @municipe = Municipe.new
    @municipe.build_endereco
  end

  def create
    @municipe = Municipe.new(municipe_params)
    if @municipe.save
      saved_or_updated
    else
      failed('new')
    end
  end

  def update
    if @municipe.update(municipe_params)
      saved_or_updated
    else
      failed('edit')
    end
  end

  def show; end

  def edit; end

  private

  def set_municipe
    @municipe = Municipe.find_or_initialize_by(id: params[:id])
  end

  def saved_or_updated
    flash[:success] = I18n.t('messages.saved')
    redirect_to municipes_path
  end

  def failed(action)
    flash.now[:danger] = @municipe.errors.full_messages.to_sentence
    render action
  end

  def municipe_params
    params.require(:municipe).permit(:name, :cpf, :cns, :email, :birthdate, :phone, :photo, :status, endereco_attributes: [:id, :zipcode, :address, :neighborhood, :city, :state, :complement, :ibge_code])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/enderecos/_form.html.erb
<div class="row">
	<div class="col">
		<%= f.label :zipcode, "CEP", class: "control-label" %>
		<%= f.text_field :zipcode, class: "form-control" %>
	</div>
</div>
<div class="row">
	<div class="col">
		<%= f.label :address, "Logradouro", class: "control-label" %>
		<%= f.text_field :address, class: "form-control" %>
	</div>
	<div class="col">
		<%= f.label :neighborhood, "Bairro", class: "control-label" %>
		<%= f.text_field :neighborhood, class: "form-control" %>
	</div>
</div>
<div class="row">
	<div class="col">
		<%= f.label :city, "Cidade", class: "control-label" %>
		<%= f.text_field :city, class: "form-control" %>
	</div>
	<div class="col">
		<%= f.label :complement, "Complemento", class: "control-label" %>
		<%= f.text_field :complement, class: "form-control" %>
	</div>
</div>
<div class="row">
	<div class="col">
		<%= f.label :state, "Estado", class: "control-label" %>
		<%= f.text_field :state, class: "form-control" %>
	</div>
	<div class="col">
		<%= f.label :ibge_code, "Código IBGE", class: "control-label" %>
		<%= f.text_field :ibge_code, class: "form-control" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= I18n.t("global.title")  %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar'%>
    <%= render partial: 'shared/error_messages'%>
    <%= yield %>
  </body>
</html>

app/views/municipes/_form.html.erb
<h3 class="title"> Cadastro de Munícipe </h3>
<%= form_for @municipe do |f| %>
	<div class="container">
		<div class="row">
			<div class="col">
				<%= f.label :name, I18n.t('activerecord.attributes.municipe.name'), class: "control-label" %>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div class="col">
				<%= f.label :phone, I18n.t('activerecord.attributes.municipe.phone'), class: "control-label" %>
				<%= f.text_field :phone, class: "form-control" %>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<%= f.label :email, I18n.t('activerecord.attributes.municipe.email'), class: "control-label" %>
				<%= f.text_field :email, class: "form-control" %>
			</div>
			<div class="col">
				<%= f.label :birthdate, I18n.t('activerecord.attributes.municipe.birthdate'), class: "control-label" %>
				<%= f.date_field :birthdate, class: "form-control" %>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<%= f.label :cpf, I18n.t('activerecord.attributes.municipe.cpf'), class: "control-label" %>
				<%= f.text_field :cpf, class: "form-control" %>
			</div>
			<div class="col">
				<%= f.label :cns, I18n.t('activerecord.attributes.municipe.cns'), class: "control-label" %>
				<%= f.text_field :cns, class: "form-control" %>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<%= f.label :photo, I18n.t('activerecord.attributes.municipe.photo'), class: "control-label" %>
				<%= f.file_field :photo, class: "form-control" %>
			</div>
			<div class="col">
				<%= f.label :status, I18n.t('activerecord.attributes.municipe.status.one'), class: "control-label" %>
				<%= f.select(:status, [[I18n.t('activerecord.attributes.municipe.status.active'), true], [I18n.t('activerecord.attributes.municipe.status.inactive'), false]], {}, { class: 'form-select' }) %>
			</div>
		</div>
		<div class="nested-fields">
			<%= f.fields_for :endereco do |endereco_form| %>
				<%= render "enderecos/form", f: endereco_form %>
			<% end %>
		</div>
		<div class="col">
			<%= f.submit I18n.t('titles.actions.save'), class: "btn btn-default btn-primary" %>
			<%= f.submit I18n.t('titles.actions.back'), class: "btn btn-default btn-secondary" %>

		</div>
	</div>
<% end %>

app/views/municipes/edit.html.erb
<%= render "form" %>

app/views/municipes/index.html.erb
<% if @municipes.any? %>
<h3 class="title"> Munícipes Cadastrados </h3>
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th><%= I18n.t("activerecord.attributes.municipe.name")  %></th>
				<th><%= I18n.t("activerecord.attributes.municipe.email")  %></th>
				<th><%= I18n.t("activerecord.attributes.municipe.phone")  %></th>
				<th><%= I18n.t("activerecord.attributes.municipe.birthdate")  %></th>
				<th><%= I18n.t("activerecord.attributes.municipe.cpf")  %></th>
				<th><%= I18n.t("activerecord.attributes.municipe.cns")  %></th>
				<th><%= I18n.t("activerecord.attributes.municipe.status.one")  %></th>
				<th><%= I18n.t("titles.actions.one")  %></th>
			</tr>
		</thead>

		<tbody>
			<% @municipes.each do |municipe| %>
			<tr>
				<td><%= municipe.name %></td>
				<td><%= municipe.email %></td>
				<td><%= municipe.phone %></td>
				<td><%= municipe.birthdate %></td>
				<td><%= municipe.cpf %></td>
				<td><%= municipe.cns %></td>
				<td><%= municipe.status %></td>
				<td><%= link_to I18n.t('titles.actions.edit'), edit_municipe_path(municipe), class: "btn btn-default btn-success" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/municipes/new.html.erb
<%= render "form" %>

app/views/shared/_error_messages.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		<%= value %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand"><h3><%= I18n.t("activerecord.models.municipe.other") %></h3></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/municipes"><%= I18n.t("static_pages.navbar.list")  %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/municipes/new"><%= I18n.t("static_pages.navbar.add")  %></a>
        </li>
      </ul>
      <form class="d-grid gap-2 d-md-block">
        <% if current_user %>
          <%= link_to I18n.t('titles.actions.edit'), edit_user_registration_path, class: "btn btn-outline-primary" %>
          <%= link_to I18n.t('titles.actions.exit'), destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
        <% end %>
      </form>
    </div>
  </div>
</nav>